name: Ubuntu GUI + noVNC + Playit

on:
  workflow_dispatch:

jobs:
  run-ubuntu-gui:
    runs-on: ubuntu-latest

    steps:
    - name: Cài Desktop + Tools
      run: |
        sudo apt update && sudo apt install -y \
          xfce4 xfce4-goodies x11vnc novnc websockify \
          tightvncserver firefox xterm curl gpg

    - name: Cài Playit Agent
      run: |
        curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
        sudo apt update && sudo apt install -y playit

    - name: Cấu hình VNC + XFCE
      run: |
        mkdir -p ~/.vnc
        echo -e "123456\n123456\nn" | vncpasswd

        echo '#!/bin/bash' > ~/.vnc/xstartup
        echo 'xrdb $HOME/.Xresources' >> ~/.vnc/xstartup
        echo 'startxfce4 &' >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

        vncserver :1
        vncserver -kill :1

    - name: Khởi động GUI + VNC + noVNC
      run: |
        export DISPLAY=:1
        vncserver :1
        sleep 5
        x11vnc -display :1 -nopw -forever -bg
        websockify --web=/usr/share/novnc/ 8080 localhost:5901 &

    - name: Chạy Playit tunnel
      run: |
        playit start > playit.log &
        sleep 10
        echo "[+] Link từ playit:"
        cat playit.log | grep https || tail playit.log

    - name: Giữ cho workflow sống
      run: sleep 108000
