name: Playit GUI Tunnel (Ubuntu XFCE + noVNC)

on:
  workflow_dispatch:

jobs:
  ubuntu-gui-playit:
    runs-on: ubuntu-latest

    steps:
    - name: Cài XFCE + noVNC + Firefox
      run: |
        echo "[+] Cài desktop + tools..."
        sudo apt update && sudo apt install -y \
          xfce4 xfce4-goodies x11vnc novnc websockify \
          tightvncserver firefox xterm curl gpg

    - name: Cài Playit
      run: |
        echo "[+] Thêm repo Playit..."
        curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
        echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
        sudo apt update && sudo apt install -y playit

    - name: Cấu hình Desktop và VNC
      run: |
        echo "[+] Cấu hình XFCE cho VNC..."
        mkdir -p ~/.vnc
        echo '#!/bin/bash' > ~/.vnc/xstartup
        echo 'xrdb $HOME/.Xresources' >> ~/.vnc/xstartup
        echo 'startxfce4 &' >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

        echo "[+] Tạo shortcut Firefox..."
        mkdir -p ~/.local/share/applications
        echo '[Desktop Entry]' > ~/.local/share/applications/firefox.desktop
        echo 'Version=1.0' >> ~/.local/share/applications/firefox.desktop
        echo 'Name=Firefox' >> ~/.local/share/applications/firefox.desktop
        echo 'GenericName=Web Browser' >> ~/.local/share/applications/firefox.desktop
        echo 'Exec=firefox %u' >> ~/.local/share/applications/firefox.desktop
        echo 'Icon=firefox' >> ~/.local/share/applications/firefox.desktop
        echo 'Terminal=false' >> ~/.local/share/applications/firefox.desktop
        echo 'Type=Application' >> ~/.local/share/applications/firefox.desktop
        echo 'Categories=Network;WebBrowser;' >> ~/.local/share/applications/firefox.desktop
        chmod +x ~/.local/share/applications/firefox.desktop

        echo "[+] Khởi tạo VNC lần đầu..."
        vncserver :1 && vncserver -kill :1

        echo "[+] Khởi động x11vnc + noVNC..."
        x11vnc -display :1 -forever -nopw -bg
        websockify --web=/usr/share/novnc/ 8080 localhost:5901 &

    - name: Bật Playit tunnel
      run: playit start &

    - name: Giữ phiên hoạt động
      run: sleep 10800
